export const articleConstant = {
  FETCH_ARTICLE_REQUEST: 'FETCH_ARTICLE_REQUEST',
  FETCH_ARTICLE_SUCCESS: 'FETCH_ARTICLE_SUCCESS',
  FETCH_ARTICLE_FAILURE: 'FETCH_ARTICLE_FAILURE',

  SAVE_INFO_POST: 'SAVE_INFO_POST',
};
