export const articleConstant = {
  FETCH_ARTICLE_REQUEST: 'FETCH_ARTICLE_REQUEST',
  FETCH_ARTICLE_SUCCESS: 'FETCH_ARTICLE_SUCCESS',
  FETCH_ARTICLE_FAILURE: 'FETCH_ARTICLE_FAILURE',

  FETCH_SPECIFIC_ARTICLE_REQUEST: 'FETCH_SPECIFIC_ARTICLE_REQUEST',
  FETCH_SPECIFIC_ARTICLE_SUCCESS: 'FETCH_SPECIFIC_ARTICLE_SUCCESS',
  FETCH_SPECIFIC_ARTICLE_FAILURE: 'FETCH_SPECIFIC_ARTICLE_FAILURE',

  GET_SIGN_URL_REQUEST: 'GET_SIGN_URL_REQUEST',
  GET_SIGN_URL_SUCCESS: 'GET_SIGN_URL_SUCCESS',
  GET_SIGN_URL_FAILURE: 'GET_SIGN_URL_FAILURE',

  UPLOAD_IMAGE_REQUEST: 'UPLOAD_IMAGE_REQUEST',
  UPLOAD_IMAGE_SUCCESS: 'UPLOAD_IMAGE_SUCCESS',
  UPLOAD_IMAGE_FAILURE: 'UPLOAD_IMAGE_FAILURE',

  CREATE_NEW_POST_REQUEST: 'CREATE_NEW_POST_REQUEST',
  CREATE_NEW_POST_SUCCESS: 'CREATE_NEW_POST_SUCCESS',
  CREATE_NEW_POST_FAILURE: 'CREATE_NEW_POST_FAILURE',

  UPDATE_POST_REQUEST: 'UPDATE_POST_REQUEST',
  UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',
  UPDATE_POST_FAILURE: 'UPDATE_POST_FAILURE',

  DELETE_POST_REQUEST: 'DELETE_POST_REQUEST',
  DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
  DELETE_POST_FAILURE: 'DELETE_POST_FAILURE',

  LIKE_POST_REQUEST: 'LIKE_POST_REQUEST',
  LIKE_POST_SUCCESS: 'LIKE_POST_SUCCESS',
  LIKE_POST_FAILURE: 'LIKE_POST_FAILURE',

  GET_COMMENT_POST_REQUEST: 'GET_COMMENT_POST_REQUEST',
  GET_COMMENT_POST_SUCCESS: 'GET_COMMENT_POST_SUCCESS',
  GET_COMMENT_POST_FAILURE: 'GET_COMMENT_POST_FAILURE',

  COMMENT_POST_REQUEST: 'COMMENT_POST_REQUEST',
  COMMENT_POST_SUCCESS: 'COMMENT_POST_SUCCESS',
  COMMENT_POST_FAILURE: 'COMMENT_POST_FAILURE',

  FOLLOW_USER_REQUEST: 'FOLLOW_USER_REQUEST',
  FOLLOW_USER_SUCCESS: 'FOLLOW_USER_SUCCESS',
  FOLLOW_USER_FAILURE: 'FOLLOW_USER_FAILURE',
};
