export const postConstant = {
  FETCH_POST_REQUEST: 'FETCH_POST_REQUEST',
  FETCH_POST_SUCCESS: 'FETCH_POST_SUCCESS',
  FETCH_POST_FAILURE: 'FETCH_POST_FAILURE',
  FETCH_MORE_POST_SUCCESS: 'FETCH_MORE_POST_SUCCESS',

  FETCH_SPECIFIC_POST_REQUEST: 'FETCH_SPECIFIC_POST_REQUEST',
  FETCH_SPECIFIC_POST_SUCCESS: 'FETCH_SPECIFIC_POST_SUCCESS',
  FETCH_SPECIFIC_POST_FAILURE: 'FETCH_SPECIFIC_POST_FAILURE',
};
