export const postConstant = {
  FETCH_POST_REQUEST: 'FETCH_POST_REQUEST',
  FETCH_POST_SUCCESS: 'FETCH_POST_SUCCESS',
  FETCH_POST_FAILURE: 'FETCH_POST_FAILURE',

  FETCH_MORE_POST_REQUEST: 'FETCH_MORE_POST_REQUEST',
  FETCH_MORE_POST_SUCCESS: 'FETCH_MORE_POST_SUCCESS',
  FETCH_MORE_POST_FAILURE: 'FETCH_MORE_POST_FAILURE',

  FETCH_SPECIFIC_POST_REQUEST: 'FETCH_SPECIFIC_POST_REQUEST',
  FETCH_SPECIFIC_POST_SUCCESS: 'FETCH_SPECIFIC_POST_SUCCESS',
  FETCH_SPECIFIC_POST_FAILURE: 'FETCH_SPECIFIC_POST_FAILURE',

  FETCH_USER_POST_REQUEST: 'FETCH_USER_POST_REQUEST',
  FETCH_USER_POST_SUCCESS: 'FETCH_USER_POST_SUCCESS',
  FETCH_USER_POST_FAILURE: 'FETCH_USER_POST_FAILURE',

  DELETE_USER_POST_REQUEST: 'DELETE_USER_POST_REQUEST',
  DELETE_USER_POST_SUCCESS: 'DELETE_USER_POST_SUCCESS',
  DELETE_USER_POST_FAILURE: 'DELETE_USER_POST_FAILURE',

  SAVE_INFO_POST: 'SAVE_INFO_POST',
};
