export const UserConstant = {
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGIN_FACEBOOK_REQUEST: 'LOGIN_FACEBOOK_REQUEST',
  LOGIN_FACEBOOK_SUCCESS: 'LOGIN_FACEBOOK_SUCCESS',
  LOGIN_FACEBOOK_FAILURE: 'LOGIN_FACEBOOK_FAILURE',

  LOGIN_GOOGLE_REQUEST: 'LOGIN_GOOGLE_REQUEST',
  LOGIN_GOOGLE_SUCCESS: 'LOGIN_GOOGLE_SUCCESS',
  LOGIN_GOOGLE_FAILURE: 'LOGIN_GOOGLE_FAILURE',

  LOGIN_GITHUB_REQUEST: 'LOGIN_GITHUB_REQUEST',
  LOGIN_GITHUB_SUCCESS: 'LOGIN_GITHUB_SUCCESS',
  LOGIN_GITHUB_FAILURE: 'LOGIN_GITHUB_FAILURE',

  LOGIN_WITH_SOCIAL_REQUEST: 'LOGIN_WITH_SOCIAL_REQUEST',
  LOGIN_WITH_SOCIAL_SUCCESS: 'LOGIN_WITH_SOCIAL_SUCCESS',
  LOGIN_WITH_SOCIAL_FAILURE: 'LOGIN_WITH_SOCIAL_FAILURE',

  GET_USER_INFO_REQUEST: 'GET_USER_INFO_REQUEST',
  GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
  GET_USER_INFO_FAILURE: 'GET_USER_INFO_FAILURE',

  CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  UPDATE_USER_INFO_REQUEST: 'UPDATE_USER_INFO_REQUEST',
  UPDATE_USER_INFO_SUCCESS: 'UPDATE_USER_INFO_SUCCESS',
  UPDATE_USER_INFO_FAILURE: 'UPDATE_USER_INFO_FAILURE',

  GET_USER_INFO_BY_ID_REQUEST: 'GET_USER_INFO_BY_ID_REQUEST',
  GET_USER_INFO_BY_ID_SUCCESS: 'GET_USER_INFO_BY_ID_SUCCESS',
  GET_USER_INFO_BY_ID_FAILURE: 'GET_USER_INFO_BY_ID_FAILURE',

  LOGOUT: 'LOGOUT',
  SHOW_MODAL_SIGN_IN: 'SHOW_MODAL_SIGN_IN',
  CLEAR_USER_STATE: 'CLEAR_USER_STATE',
};
